# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-10 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=30, unique=True, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d')),
                ('mac', models.CharField(max_length=40, verbose_name=b'MAC\xe5\x9c\xb0\xe5\x9d\x80')),
                ('outer_ip', models.CharField(blank=True, max_length=40, null=True, verbose_name=b'\xe5\xa4\x96\xe7\xbd\x91\xe5\x9c\xb0\xe5\x9d\x80')),
                ('os_platform', models.CharField(max_length=20, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe5\xb9\xb3\xe5\x8f\xb0')),
                ('os_type', models.CharField(max_length=20, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb3\xbb\xe7\xbb\x9f')),
                ('os_version', models.CharField(max_length=20, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x89\x88\xe6\x9c\xac')),
                ('os_kernel', models.CharField(max_length=30, verbose_name=b'\xe5\x86\x85\xe6\xa0\xb8\xe7\x89\x88\xe6\x9c\xac')),
                ('cpu_arch', models.CharField(max_length=30, verbose_name=b'CPU\xe6\x9e\xb6\xe6\x9e\x84')),
                ('cpu_physical_num', models.IntegerField(verbose_name=b'CPU\xe7\x89\xa9\xe7\x90\x86\xe6\xa0\xb8\xe5\xbf\x83\xe6\x95\xb0')),
                ('cpu_logical_num', models.IntegerField(verbose_name=b'CPU\xe9\x80\xbb\xe8\xbe\x91\xe6\xa0\xb8\xe5\xbf\x83\xe6\x95\xb0')),
                ('mem_total', models.CharField(max_length=30, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe5\xa4\xa7\xe5\xb0\x8f')),
            ],
        ),
    ]
