# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-13 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='cpu_arch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'CPU\xe6\x9e\xb6\xe6\x9e\x84'),
        ),
        migrations.AlterField(
            model_name='host',
            name='cpu_physical_num',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'CPU\xe7\x89\xa9\xe7\x90\x86\xe6\xa0\xb8\xe5\xbf\x83\xe6\x95\xb0'),
        ),
        migrations.AlterField(
            model_name='host',
            name='mac',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name=b'MAC\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem_total',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe5\x86\x85\xe5\xad\x98\xe5\xa4\xa7\xe5\xb0\x8f'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_kernel',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe5\x86\x85\xe6\xa0\xb8\xe7\x89\x88\xe6\x9c\xac'),
        ),
        migrations.AlterField(
            model_name='host',
            name='os_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\x89\x88\xe6\x9c\xac'),
        ),
    ]
